### ISSUE TITLE
Not working  on localhost input

### ISSUE THREAD

**Issue by jet1276** [logstash-plugins/logstash-input-tcp#91] opened 2017-10-31 10:52 UTC
Hi,

Whenever I try to receive data which sent from another system, I am able to see the data  in output.

But if I try to receive data which was sent from the same system via Rsyslog, I am not able to get anything in output.

- Version: 5.0.2
- Operating System: CentOS 7.4
- Config File:
`input {
  tcp {
    port => 5000
  }
}
output {
  file {
        path => "/transfer.out"
}
}
`

**Comment by jakelandis** [comment] 2017-10-31 16:21
Can you try to send an event via netcat ?  
```
echo "hello world" | nc localhost 5000
```

I am going to close this issue since I can not reproduce it, and there is not any special logic around localhost.  If you still feel this is a bug, please re open with a reproducible case (like using netcat) and include the specific version of the tcp input. 

If you think this may be an issue with your local setup, you can reach out on our forums where others may have had the same issue: https://discuss.elastic.co/c/logstash

**Closed by jakelandis** 2017-10-31 16:21 UTC
