### ISSUE TITLE
SSL exceptions trigger close for unrelated connections

### ISSUE THREAD

**Issue by bobrik** [logstash-plugins/logstash-input-tcp#23] opened 2015-10-27 15:34 UTC
Running logstash 2.0.0-rc1.

Config:

```
input {
  tcp {
    host       => "0.0.0.0"
    port       => 12121
    ssl_enable => true
    ssl_cert   => "/etc/logstash/ssl/cert"
    ssl_key    => "/etc/logstash/ssl/key"
  }
}

filters {
  grok {
    match => {
      "message" => "<%{POSINT:priority}>%{SYSLOGLINE}"
    }
    overwrite => [ "message" ]
  }

  date {
    match => [ "timestamp8601", "ISO8601" ]
  }

  mutate {
    remove_field => [ "timestamp8601", "priority" ]
    add_field => {
      "app" => "myapp"
    }
  }
}

output {
  stdout {
    codec => "rubydebug"
  }
}
```

Steps to reproduce:

1. Connect TLS client (I used syslog-ng), start producing messages.
2. Connect with plain text, write some garbage.
3. TLS connection is closed.

Another funny one:

1. Connect, then immediately disconnect
2. Randomly crash logstash

```
SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Socket closed>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:108:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:80:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.rc1-java/lib/logstash/pipeline.rb:180:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.rc1-java/lib/logstash/pipeline.rb:174:in `start_input'"], :level=>:error}
IOError: closed stream
                  peeraddr at org/jruby/ext/socket/RubyIPSocket.java:95
                  peeraddr at org/jruby/ext/openssl/SSL.java:209
                      peer at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.rc1-java/lib/logstash/util/socket_peer.rb:5
             handle_socket at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:162
  server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140
```

**Comment by bobrik** [comment] 2015-10-27 15:42
I don't think there should be any errors for immediate disconnect.

**Comment by hamishforbes** [comment] 2015-10-30 10:19
I'm seeing the same behaviour in 2.0.0 final and have had to rollback to 1.5

Minimal config

```
input {
    tcp {
              port => "10516"
            ssl_enable => true
            ssl_cert => '/etc/pki/tls/certs/localhost.crt'
            ssl_key => '/etc/pki/tls/private/localhost.key'
          }
}
output {
    stdout { codec => rubydebug }
}
```

Connect via openssl s_client

```
openssl s_client -connect 127.0.0.1:10516
```

Then send some plain text bytes

```
echo 'broken connection!' | nc 127.0.0.1 10516
```

SSL connection gets closed:

```
Accepted connection {:client=>"127.0.0.1:52146", :server=>"0.0.0.0:10516", :level=>:debug, :file=>"logstash/inputs/tcp.rb", :line=>"139", :method=>"server_connection_thread"}
config LogStash::Codecs::Line/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"128", :method=>"config_init"}

SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Unrecognized SSL message, plaintext connection?>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:108:in `run_server'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:80:in `run'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:180:in `inputworker'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:174:in `start_input'"], :level=>:error, :file=>"logstash/inputs/tcp.rb", :line=>"113", :method=>"run_server"}
Connection closed {:client=>"127.0.0.1:52146", :level=>:debug, :file=>"logstash/inputs/tcp.rb", :line=>"157", :method=>"handle_socket"}
```

**Comment by pbmsys** [comment] 2015-11-02 09:11
Any updates on this issue?
I have the exact same errors in my logs. Logstash throws a SSL Error and closes it self.
Not practical in a production env. :)

**Comment by chandlermelton** [comment] 2015-11-04 19:03
+1

**Comment by bobrik** [comment] 2015-11-04 19:09
I've also seen timeouts on connections to logstash, connections were in `SYN_SENT` on sending side.

Switched to `syslog-ng` with kafka output, very happy about it.

**Comment by pbmsys** [comment] 2015-11-06 06:35
@bobrik is it both on logstash 2.0 and 1.5 you have seen this pattern?

**Comment by AlexBaker-** [comment] 2015-11-06 11:37
Confirmed, same exact issue as described in OP with Logstash 2.0.0, Ubuntu 14.04.3 Trusty.

**Comment by chandlermelton** [comment] 2015-11-06 16:19
@pbmsys I am seeing the errors on 1.5 as well as 2.0. It is only on 2.0 that Logstash stops running.

**Comment by pbmsys** [comment] 2015-11-09 06:42
@chandlermelton same here, ít forces Logstash 2.0 to crash, while 1.5 soldiers on.

**Comment by ranman** [comment] 2015-11-11 03:36
This doesn't crash 1.5 but does crash 2.0 for me. Kind of a big deal if this plugin crashes all of logstash.

**Comment by pbmsys** [comment] 2015-11-12 12:13
Anyone found a solution yet?

**Comment by pbmsys** [comment] 2015-11-18 07:34
Any Updates?

**Comment by AlexBaker-** [comment] 2015-11-20 12:07
Proposed a fix in pull request #25

**Comment by pbmsys** [comment] 2015-11-24 14:51
@AlexBaker- Did you get anywhere with Jenkins? would be nice with temp fix so we could get on with the 2.0.0 version of EL and Logstash

**Comment by AlexBaker-** [comment] 2015-11-24 15:11
@pbmsys Not yet.  @purbon just mentioned it in #25 a few minutes ago.  I'll update once we figure this out.

**Comment by pbmsys** [comment] 2015-11-24 15:14
@AlexBaker-  Aah yeah, i see, looking forward :)

**Comment by AlexBaker-** [comment] 2015-11-24 18:31
![Aww yeah](https://t0.gstatic.com/images?q=tbn:ANd9GcRb_6UY4OPBzKa0JeCc7RbGJ_AKy50zFYzXLHQFXaMPnIp8YmCKXbI_)

**Comment by purbon** [comment] 2015-11-24 18:31
@AlexBaker- happy to help, also @jordansissel ! closing this issue for now

**Comment by jordansissel** [comment] 2015-11-24 18:31
Woohoo!

**Closed by purbon** 2015-11-24 18:31 UTC

**Comment by pbmsys** [comment] 2015-11-30 06:51
In logstash 2.1 i still receive the following error:

{:timestamp=>"2015-11-30T07:50:31.823000+0100", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: Socket closed>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.5/lib/logstash/inputs/tcp.rb:108:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.5/lib/logstash/inputs/tcp.rb:80:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}


After the error logstash eventually exits with the following:

IOError: closed stream
                  peeraddr at org/jruby/ext/socket/RubyIPSocket.java:95
                  peeraddr at org/jruby/ext/openssl/SSL.java:209
                      peer at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/util/socket_peer.rb:5
             handle_socket at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.5/lib/logstash/inputs/tcp.rb:166
  server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.5/lib/logstash/inputs/tcp.rb:140


So looks the same as before?

**Comment by purbon** [comment] 2015-11-30 07:42
@pbmsys can you share your config? would really love to reproduce it.

**Comment by pbmsys** [comment] 2015-11-30 07:52
@purbon  sure no problem:

my conf file:
input {
  tcp {
    codec => json_lines { charset => "CP1252" }
    port => 3515
    ssl_cacert => "/etc/pki/tls/certs/cacert.crt"
    ssl_cert => "/etc/pki/tls/certs/cert.crt"
    ssl_key => "/etc/pki/tls/private/key.key"
    ssl_enable => true
  }
}
output {
  elasticsearch {
	hosts => ["some.server:9200", "some.server2:9200", "some.server3.local:9200"]
}
}

**Comment by purbon** [comment] 2015-11-30 07:54
@pbmsys does this happen right at the beginning, after a few logs received?

**Comment by pbmsys** [comment] 2015-11-30 07:56
@purbon After some logs received, usually within 2 minutes of starting logstash.

**Comment by purbon** [comment] 2015-11-30 08:05
@pbmsys can you run for this two minutes with DEBUG=1 and share your logs? I wonder if this is related to have a poison message and the input not being able to handle it properly. does this makes sense to you?

**Comment by pbmsys** [comment] 2015-11-30 08:33
@purbon Like this?
./logstash -f /etc/logstash/conf.d/01-nxlog-input.conf -l /root/logstash_debug.log --debug

I get the following:

Output in console: 
[Console output.txt](https://github.com/logstash-plugins/logstash-input-tcp/files/47067/Console.output.txt)

The Logfile:
[logstash_debug.txt](https://github.com/logstash-plugins/logstash-input-tcp/files/47069/logstash_debug.txt)

**Comment by purbon** [comment] 2015-11-30 08:35
@pbmsys exactly like this, thanks a lot, this is really helpful.

**Comment by pbmsys** [comment] 2015-11-30 09:32
@purbon Super, let me know if you need anything else :)

**Comment by pbmsys** [comment] 2015-12-02 07:13
@purbon Did you manage to recreate the errors? or do you need more info?

**Comment by purbon** [comment] 2015-12-02 07:36
@pbmsys not yet, need to fetch a windows machine :+1:  before because in unix is not happening, or at less I still can not reproduce.

**Comment by shitler25oki** [comment] 2015-12-07 04:02
@purbon I too am experiencing similar behavior as describe by @pbmsys.  I'm looking to put this in our production environment.

Version
RHEL 6.6
Java 1.8
logstash 2.1.0
logstash  3.0.0.dev

/etc/logstash/conf.d/ssltest.conf
input {
  tcp {
    port       => 5140
    type       => "ssl_test"
    ssl_enable => true
    ssl_verify => false
    ssl_key    => "/etc/logstash/certs/logstash.key"
    ssl_cert   => "/etc/logstash/certs/logstash.crt"
  }
}

output { 
  stdout { 
    codec => rubydebug
  } 
}

/etc/rsyslog.d/ssltest.conf
$DefaultNetstreamDriverCAFile /etc/pki/tls/certs/ca-bundle.crt
$DefaultNetstreamDriver gtls # use gtls netstream driver
$ActionSendStreamDriverMode 1 # require TLS for the connection
$ActionSendStreamDriverAuthMode anon # server is NOT authenticated
*.* @@localhost:5514 # send (all) messages

Resulting stacktrace logstash 3.0.0.dev
"org/jruby/ext/socket/RubyIPSocket.java:95:in `peeraddr'", 
"org/jruby/ext/openssl/SSL.java:209:in `peeraddr'", 
"/opt/IdeaProjects/logstash/logstash-core/lib/logstash/util/socket_peer.rb:5:in `peer'", 
"/opt/IdeaProjects/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:171:in `handle_socket'", "/opt/IdeaProjects/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:144:in `server_connection_thread'"

Resulting stacktrace logstash 2.1.0
IOError: closed stream
peeraddr at org/jruby/ext/socket/RubyIPSocket.java:95
peeraddr at org/jruby/ext/openssl/SSL.java:209
peer at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/util/socket_peer.rb:5
handle_socket at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:162
server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140

Simple bash script to reproduce
count=0
while :
do
let count+=1
logger rsyslog iteration ${count}
sleep 1
telnet localhost 5514 << EOF
telnet
EOF
sleep 1
done

Catching IOError in tcp.rb prevents logstash from stopping
161 rescue EOFError
162   @logger.debug? && @logger.debug("Connection closed", :client => socket.peer)
163 rescue Errno::ECONNRESET
164   @logger.debug? && @logger.debug("Connection reset by peer", :client => socket.peer)
165 rescue IOError => e
166   @logger.error("Danger Will Robinson", :exception => e, :backtrace => e.backtrace)
167 rescue OpenSSL::SSL::SSLError => e
168   # Fixes issue #23
169   @logger.error("SSL Error", :exception => e, :backtrace => e.backtrace)
170   socket.close rescue nil

**Comment by AlexBaker-** [comment] 2015-12-07 09:25
@shitler25oki You're using an older version of the plugin before the SSL fixes:

```
server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140
```

Notice it says `logstash-input-tcp-2.0.4`.  The current version is 3.0.0.  Run `/opt/logstash/bin/plugin update logstash-input-tcp`, restart Logstash and see if the problem remains.

That being said, I've tried a few ways in 3.0.0 to crash Logstash with bad SSL data (no cert, malformed cert, plaintext on SSL port, etc.), and I can't make it do any worse than output an "SSL Error" exception catch.

**Comment by shitler25oki** [comment] 2015-12-07 15:51
@AlexBaker- Thank you for pointing out that I was using an older version of the plugin with logstash 2.1.0.  However, after updating the logstash-input-tcp plugin I still receive the same behavior.  I am able to reproduce this quite easily on all boxes that I have tried which makes me curious exactly what I'm doing differently.

Here is the behavior exhibited by logstash after updating to logstash-input-tcp 3.0.0:

[root@3f2f42b3bc04 conf.d]# logger test 1

[root@3f2f42b3bc04 conf.d]# {
       "message" => "<13>Dec  7 10:43:10 3f2f42b3bc04 logger: test 1",
      "@version" => "1",
    "@timestamp" => "2015-12-07T15:43:10.755Z",
          "host" => "172.17.0.1",
          "port" => 49419,
          "type" => "ssl_test"
}

[root@3f2f42b3bc04 conf.d]# telnet localhost 5514
Trying ::1...
Connected to localhost.
Escape character is '^]'.
test 1

Connection closed by foreign host.

[root@3f2f42b3bc04 conf.d]# SSL Error {:exception=>#\<OpenSSL::SSL::SSLError: Unrecognized SSL message, plaintext connection?>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}

IOError: closed stream
                  peeraddr at org/jruby/ext/socket/RubyIPSocket.java:95
                  peeraddr at org/jruby/ext/openssl/SSL.java:209
                      peer at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/util/socket_peer.rb:5
             handle_socket at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:171
  server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:144

[1]+  Exit 1                  /opt/logstash/bin/logstash -f /etc/logstash/conf.d

Here is what I get after I modify tcp.rb in logstash-input-tcp 3.0.0 to catch IOError:

[root@3f2f42b3bc04 conf.d]# logger test 2

[root@3f2f42b3bc04 conf.d]# {
       "message" => "<13>Dec  7 10:46:21 3f2f42b3bc04 logger: test 2",
      "@version" => "1",
    "@timestamp" => "2015-12-07T15:46:21.633Z",
          "host" => "172.17.0.1",
          "port" => 49423,
          "type" => "ssl_test"
}

[root@3f2f42b3bc04 conf.d]# telnet localhost 5514
Trying ::1...
Connected to localhost.
Escape character is '^]'.
test 2
Connection closed by foreign host.

[root@3f2f42b3bc04 conf.d]# SSL Error {:exception=>#\<OpenSSL::SSL::SSLError: Unrecognized SSL message, plaintext connection?>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}

Danger Will Robinson {:exception=>#\<IOError: stream closed>, :backtrace=>["org/jruby/RubyIO.java:2101:in `close'", "org/jruby/ext/openssl/SSLSocket.java:816:in `sysclose'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/buffering.rb:447:in `close'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:118:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}

**Comment by AlexBaker-** [comment] 2015-12-07 17:10
@shitler25oki That's strange I can't reproduce.  If I do exactly your telnet tests, this is what I get:

#### From Client
```
[user@host ~]$ telnet lstest 514
Trying x.x.x.x...
Connected to x.x.x.x.
Escape character is '^]'.
test 1
Connection closed by foreign host.
[user@host ~]$ telnet lstest 514
Trying x.x.x.x...
Connected to x.x.x.x.
Escape character is '^]'.
test 2
Connection closed by foreign host.
```

#### From Logstash
```
# /opt/logstash/bin/logstash -f tcp_ssl.conf 
Settings: Default filter workers: 2
Logstash startup completed
SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Unrecognized SSL message, plaintext connection?>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}
SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Unrecognized SSL message, plaintext connection?>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}
```

#### logstash config
```
input {
  tcp {
    port => 514
    type => "tcp-ssl"
    ssl_cert => "/etc/ssl/client.crt"
    ssl_key => "/etc/ssl/client.key"
    ssl_enable => true
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

But no crash.  We're running identical versions of everything and using identical tests.

In any case, extra exception handling never hurts.  Can you do a pull request with your exception catch, please?  Let me know if you're unable to (and include a diff of tcp.rb, too).

**Comment by chandlermelton** [comment] 2015-12-07 19:08
I am seeing the same issue as shitler25oki and pbmsys.

input
{
tcp  { codec => "json" port => "50000" ssl_verify => "false" ssl_enable => "true" ssl_extra_chain_certs => "/etc/pki/tls/certs/RootCA.cer" ssl_cert => "/etc/pki/tls/certs/logmgmt.cer" ssl_key => "/etc/pki/tls/private/logmgmt.key" }
}


/opt/logstash/bin/logstash -f /etc/logstash/conf.d/lsbroker.conf


SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Socket closed>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :level=>:error}


IOError: closed stream
                  peeraddr at org/jruby/ext/socket/RubyIPSocket.java:95
                  peeraddr at org/jruby/ext/openssl/SSL.java:209
                      peer at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/util/socket_peer.rb:5
             handle_socket at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:171
  server_connection_thread at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:144

**Comment by pbmsys** [comment] 2015-12-14 12:41
Anyone who have been able to resolve the problem? @shitler25oki Did your exception catch do the trick?

**Comment by shitler25oki** [comment] 2015-12-20 19:11
@pbmsys it did indeed do the trick for me.  If you feel like giving it a try take a look at the pull request I submitted, add the 3 lines to tcp.rb and restart logstash.

**Comment by pbmsys** [comment] 2015-12-21 09:03
Just receives a "null cert chain" after update to 3.0.0, so i am currently unable to test.
Bonkers.

**Comment by jordansissel** [comment] 2016-01-15 20:16
"null cert chain" likely  means your connecting client has provided no certificate and your server (tcp input) is attempting to verify the certificate. See #33 for the null cert chain issues.
